### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by shams2023** [three0-s/img-caption-blip2#1]
Hello author!
May I ask which system your code is running on (Linux?/Other?)
Can corresponding text descriptions be generated in batches for images in the image dataset?

**Comment by yevvonlim** [comment]
Hello, shams.

This code is running on Ubuntu and most of the code is dependent on the official repo (https://github.com/salesforce/LAVIS/tree/main/projects/blip2).
As you assumed, you can generate text descriptions in batches of images using multiple gpus using this repo.

**Comment by shams2023** [comment]
> 你好，shams。
> 
> 此代码在 Ubuntu 上运行，大部分代码依赖于官方存储库 （https://github.com/salesforce/LAVIS/tree/main/projects/blip2）。正如你所假设的，你可以使用此存储库使用多个 GPU 批量生成图像中的文本描述。

Can I run on Linux?
thanks

**Comment by yevvonlim** [comment]
Sure you can. Consider using docker image

**Comment by shams2023** [comment]
Thanks,
How effective is the text description generated for similar images? (I don't want to get the same text description, which will make it difficult for my subsequent tasks to progress)

**Comment by yevvonlim** [comment]
I think it would depend on the model you choose. As you can see in codes, you can choose specific model you will use for captioning. I used _"blip2-flan-t5-xl"_ and the resulting text description was quite satisfactory. But I am afraid to say the model is perfect enough; you should test the model and make decision by yourself.

**Comment by shams2023** [comment]
> I think it would depend on the model you choose. As you can see in codes, you can choose specific model you will use for captioning. I used _"blip2-flan-t5-xl"_ and the resulting text description was quite satisfactory. But I am afraid to say the model is perfect enough; you should test the model and make decision by yourself.

Sorry to bother you again!
I encountered the following error while running the code. How can I resolve it?:
===================================BUG REPORT===================================
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('C'), WindowsPath('/Users/sham/anaconda3/envs/szj/lib')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=117, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\Users\sham\anaconda3\envs\szj\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
C:\Users\sham\anaconda3\envs\szj\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
C:\Users\sham\anaconda3\envs\szj\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: C:\Users\sham\anaconda3\envs\szj did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
Traceback (most recent call last):
  File "D:\reid_code\Captioner\3\img-caption-blip2-main\img2text-single.py", line 8, in <module>
    import bitsandbytes
  File "C:\Users\sham\anaconda3\envs\szj\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\sham\anaconda3\envs\szj\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\sham\anaconda3\envs\szj\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\sham\anaconda3\envs\szj\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\sham\anaconda3\envs\szj\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\sham\anaconda3\envs\szj\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

Process finished with exit code 1
